version: 2.1
jobs:
    build:
        docker:
            - image: alpine:3.15
        steps:
            - run:
                  name: The First Step
                  command: |
                      echo 'Hello World!'
                      echo 'This is the delivery pipeline'

            - run:
                  name: The Second Step
                  command: |
                      echo 'This is the second step'
                      echo 'This is the second step'


